---
- name: Add mysteriumnetwork PPA
  ansible.builtin.apt_repository:
    repo: ppa:mysteriumnetwork/node
    filename: myst-node
  notify:
    - Update APT cache

- name: Force handlers
  meta: flush_handlers

- name: Install myst package
  ansible.builtin.apt:
    name: myst
    state: present
