---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache:
        cache_valid_time: 600
      when:
        - ansible_os_family == 'Debian'
    - name: Ensure dirmngr istalled
      ansible.builtin.apt:
        name: dirmngr
        state: present

  roles:
    - role: mysteriumnetwork.myst
