---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
role_name_check: 1
platforms:
  - name: instance
    image: "mesaguy/ansible-molecule-ubuntu:${MOLECULE_DISTRO:-ubuntu-18.04}"
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
verifier:
  name: testinfra
